deployment-release-manager-agent:
  name: Deployment Release Manager Agent
  type: mcp
  instructions: |
    ## Instructions
    Analyze the code scan result of the provided project and summarize the results. Based on that analysis, provide a list of recommended actions 
    and also indicate whether the project is ready for deployment or not.

    ## Sample Prompts
    - What are the recommendations for <<project_name>>?
      - Example: "What are the recommendations for my project?"
    - What are the recommendations for <<project_name>> with high test coverage?
      - Example: "What are the recommendations for my project with high test coverage?"
    - What are the recommendations for <<project_name>> with high test coverage and high code quality?
      - Example: "What are the recommendations for my project with high test coverage and high code quality?"
  servers: [
    {
      'name': 'scan_result_server',
      'command': 'python3.11',
      'args': [ 'mcp_servers/scan_results.py' ],
      'description': 'Security scanning and analysis tools'
    }
  ]
  system_prompt: |
    You are a helpful assistant with access to code scan result tool. 
    Analyze the code scan result of the provided project and summarize the results. If the prompt already has the scan results, use those results directly.
    Based on that analysis, provide a list of recommended actions 
    and also indicate whether the project is ready for deployment or not.
devops-code-remediation-agent:
  name: DevOps Code Remediation Agent
  type: bedrock
  instructions: |
    ## Instructions
    Provide the giturl and branch of the repository to be scanned. This agent will scan the repository and provide the results.
    
    ## Sample Prompt
    - Help me analyze the git url <<giturl>> and branch <<branch>> of the repository <<repository_name>> for any code issues.
      - Example: "Help me analyze the git url https://github.com/example/project.git and branch main of the repository project-name for any code issues."
    - Provide me coding best practice in <<programming language>>
      - Example: "Provide me coding best practice in Python."
      - Example: "Provide me coding best practice in JavaScript."
    - Help me analyze the git url <<giturl>> and branch <<branch>> of the repository <<repository_name>> for any code issues and provide me remediated code.
      - Example: "Help me analyze the git url https://github.com/example/webapp.git and branch development of the repository webapp for any code issues and provide me remediated code."
devops-test-case-generator-agent:
  name: Test Case Generator Agent
  type: bedrock
  instructions: |
    ## Instructions
    Provide the git URL and branch of the repository to generate unit tests. This agent will analyze the repository code and generate appropriate test cases for your files.

    ## Sample Prompts
    - Generate unit tests for my repository at <<git_url>> using branch <<branch_name>>
      - Example: "Generate unit tests for my repository at https://github.com/example/project.git using branch main"

    - Create tests for <<git_url>> with high test coverage
      - Example: "Create tests for https://github.com/myusername/api-service.git with high test coverage"
    
    - What are good testing practices for <<programming_language>>?
      - Example: "What are good testing practices for Python?"
      - Example: "What are good testing practices for JavaScript?"

    - How can I write effective unit tests for my <<framework_name>> application?
      - Example: "How can I write effective unit tests for my React application?"
      - Example: "How can I write effective unit tests for my Django application?"
name-lookup:
  name: Name Lookup
  type: mcp
  instructions: |
    ## Instructions
    Provide the name of the person to lookup. This agent will provide the results.
    If the available tools does not solve the query, then use bedrock to get the answer.

    ## Sample Prompts
    - What is the phone number of <<name>>?
      - Example: "What is the phone number of John Doe?"
    - What is the email address of <<name>>?
      - Example: "What is the email address of Jane Smith?"
    - What is the address of <<name>>?
      - Example: "What is the address of Bob Johnson?"
  servers: [
    {
      'name': 'name_lookup_server',
      'command': 'python3.11',
      'args': [ 'mcp_servers/name_lookup_server.py' ],
      'description': 'Name lookup tools'
    }
  ]
  system_prompt: |
    You are a helpful assistant with access to name lookup tools. Always provide clear responses.