devops-code-remediation-agent:
  name: DevOps Code Remediation Agent
  instructions: |
    Provide the giturl and branch of the repository to be scanned. This agent will scan the repository and provide the results.
    
    Sample prompt:    
    Help me analyze the git url <<giturl>> and branch <<branch>> of the repository <<repository_name>> for any code issues..

